-- Inserir informações na tabela tb_justificativa
INSERT INTO tb_justificativa (co_justificativa, id_justificativa, no_justificativa) VALUES 
    (1, '1', 'Tratamento de doença e de atenção à saúde do estudante'),
    (2, '2', 'Doença/óbito na família'),
    (3, '3', 'Fatos que impedem o deslocamento/acesso do estudante à escola'),
    (4, '4', 'Suspensão escolar'),
    (5, '5', 'Participação em atividade extraclasse/atividades híbridas (semipresenciais)'),
    (6, '6', 'Preconceito/Discriminação no ambiente escolar/bullying'),
    (7, '7', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas'),
    (8, '8', 'Gravidez'),
    (9, '9', 'Situação de rua'),
    (10, '10', 'Trabalho infantil'),
    (11, '11', 'Violência no ambiente escolar'),
    (12, '12', 'Trabalho do Adolescente'),
    (13, '13', 'Exploração/Abuso Sexual'),
    (14, '14', 'Desinteresse/Desmotivação pelos estudos'),
    (15, '15', 'Abandono Escolar/Desistência'),
    (16, '16', 'Questões socioeconômicas, educacionais e/ou familiares'),
    (17, '17', 'Envolvimento com drogas'),
    (18, '18', 'Envolvimento em atos infracionais'),
    (19, '19', 'Violência Intrafamiliar'),
    (20, '20', 'Situação coletiva que impede a escola de receber seus estudantes'),
    (21, '21', 'Estudante Concluiu o Ensino Médio'),
    (22, '22', 'Óbito do estudante'),
    (23, '23', 'EJA Semipresencial'),
    (24, '24', 'Outros'),
    (25, '25', 'Problemas na oferta de serviços educacionais'),
    (26, '26', 'Educação bilíngue de surdos e educação especial'),
    (27, '27', 'Outras situações específicas');


-- -- Inserir informações na tabela tb_justificativa
INSERT INTO tb_sub_justificativa (co_sub_justificativa, id_sub_justificativa, no_sub_justificativa, co_justificativa) VALUES
    (0,'1a', 'Doença/problemas físicos',1),
    (1,'1b', 'Problemas/transtornos psicológicos/mentais',1),
    (2,'1c', 'Pós-parto/Pré-natal/TPM',1),
    (3,'1d', 'Consultas de rotina/tratamento odontológico',1),
    (4,'2a', 'Doença de pessoa da família prejudicando a frequência do estudante à escola',2),
    (5,'2b', 'Óbito de pessoa da família prejudicando a frequência do estudante à escola',2),
    (6,'3a', 'Enchente',3),
    (7,'3b', 'Falta de transporte',3),
    (8,'3c', 'Estradas intransitáveis',3),
    (9,'3d', 'Violência na área onde mora/no trajeto para a escola',3),
    (10,'3e', 'Inexistência de pessoa para levar à escola',3),
    (11,'3f', 'Grande distância entre a residência e a escola',3),
    (12,'3g', 'Outro',3),
    (13,'4a', 'Suspensão escolar com tarefas domiciliares',4),
    (14,'4b', 'Suspensão escolar sem tarefas domiciliares',4),
    (15,'5a', 'Considerada atividade escolar',5),
    (16,'5b', 'Não é considerada como atividade escolar',5),
    (17,'6a', 'Preconceito/Discriminação no ambiente escolar/bullying',6),
    (18,'7a', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas: Indígenas',7),
    (19,'7b', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas: Quilombolas',7),
    (20,'7c', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas: Circenses',7),
    (21,'7d', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas: Ciganos',7),
    (22,'7e', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas: Questões religiosas',7),
    (23,'7f', 'Ausência às aulas por respeito às questões sociais, culturais, étnicas ou religiosas: Outra',7),
    (24,'8a', 'Gravidez de risco',8),
    (25,'8b', 'Não é gravidez de risco',8),
    (26,'9a', 'Situação de rua',9),
    (27,'10a', 'Trabalho infantil: A escola sabe que o estudante conta com atenção da rede de proteção local',10),
    (28,'10b', 'Trabalho infantil: A escola não sabe se o estudante conta com atenção da rede de proteção local',10),
    (29,'11a', 'Violência no ambiente escolar',11),
    (30,'12a', 'Emprego formal (a partir de 16 anos)',11),
    (31,'12b', 'Estagiário',12),
    (32,'12c', 'Trabalho informal',12),
    (33,'12d', 'Menor aprendiz',12),
    (34,'13a', 'Exploração/Abuso Sexual',13),
    (35,'14a', 'Desinteresse/Desmotivação pelos estudos',14),
    (36,'15a', 'Abandono Escolar/Desistência',15),
    (37,'16a', 'Separação dos pais',16),
    (38,'16b', 'Necessidade de cuidar de familiares (idoso, criança, pessoa com deficiência)',16),
    (39,'16c', 'Viagem com a família (trabalho sazonal/agricultura temporária/colheita/outros)',16),
    (40,'16d', 'Casamento do(a) Estudante',16),
    (41,'16e', 'Falta de uniforme/calçado/roupa adequada',16),
    (42,'16f', 'Pais “sem domínio” dos filhos/relação familiar precária',16),
    (43,'16g', 'Família desconhece as faltas do estudante às aulas',16),
    (44,'16h', 'Negligência dos pais ou responsáveis',16),
    (45,'16i', 'Estudantes com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação sem apoio/estimulação para permanecer na escola',16),
    (46,'16j', 'A escola não possui tradutor e intérprete de Libras para estudantes surdos',16),
    (47,'17a', 'Envolvimento com drogas',17),
    (48,'18a', 'Envolvimento em atos infracionais',18),
    (49,'19a', 'Violência Intrafamiliar',19),
    (50,'20a', 'Greve',20),
    (51,'20b', 'Calamidade pública que atingiu a escola ou exigiu o uso do espaço como abrigamento',20),
    (52,'20c', 'Escola sem professor',20),
    (53,'20d', 'Reforma geral da escola',20),
    (54,'20e', 'Escola fechada por situação de violência',20),
    (55,'20f', 'Falta de merenda escolar',20),
    (56,'20g', 'Outra',20),
    (57,'21a', 'Estudante Concluiu o Ensino Médio',21),
    (58,'22a', 'Óbito do estudante',22),
    (59,'23a', 'Com acompanhamento regular',23),
    (60,'23b', 'Sem acompanhamento regular',23),
    (61,'24a', 'A escola não sabe/não informou o motivo',24),
    (62,'24b', 'Não foi identificado motivo adequado nesta lista',24),
    (63,'25a', 'Inexistência de educação infantil no território em que mora',25),
    (64,'25b', 'Inexistência de ensino fundamental no território em que mora',25),
    (65,'25c', 'Inexistência de ensino médio no território onde mora',25),
    (66,'25d', 'Inexistência de serviços educacionais para acampados/ciganos/circenses/itinerantes',25),
    (67,'25e', 'Inexistência de serviços educacionais em situação de internação/privação de liberdade',25),
    (68,'25f', 'Inexistência de escola indígena no território onde mora',25),
    (69,'25g', 'Falta de vaga na escola para a etapa de ensino do estudante',25),
    (70,'25h', 'Concluiu a educação infantil/ensino fundamental/EJA e inexiste oferta imediata da etapa seguinte',25),
    (71,'26a', 'Inexistência de educação especial de estudantes com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação',26),
    (72,'26b', 'Inexistência de transporte/de gratuidade/transporte acessível à escola para beneficiário com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação',26),
    (73,'26c', 'Beneficiário com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação não frequenta a escola por resistência injustificada da família',26),
    (74,'26d', 'Inexistência de acessibilidade física/sensorial/metodológica no ambiente escolar para o beneficiário com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação',26),
    (75,'26e', 'A escola alega não possuir vaga para estudantes com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação',26),
    (76,'26f', 'Inexistência de escola (ou de vaga em escola) com tradutor e intérprete de Libras para estudantes surdos',26),
    (77,'26g', 'Beneficiário com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação apresenta impedimento de longo prazo de natureza física, mental, intelectual ou sensorial que não permite a frequência escolar',26),
    (78,'27a', 'Beneficiário sem vínculo/matrícula escolar foi encontrado, mas não quer mais estudar',27),
    (79,'27b', 'Estudante concluiu o Ensino Médio',27),
    (80,'27c', 'Óbito do estudante',27),
    (81,'27d', 'Transferência em andamento/pendente – permanecendo sem solução/aceite, após o encerramento de 02 (dois) períodos de coleta, o beneficiário será lançado como Não Localizado no município de origem do Cadastro Único da família',27),
    (82,'27e', 'Beneficiário com dados errados impedindo a identificação pela escola (nome errado/data de nascimento errada/NIS duplicado)',27)